In [37]:
#pandas
# Numpy and pandas are very useful for exploratory data analysis
#pandas is an open source library provides high performance, easy to use data structures and data analysis
#tools for the python programming language.

# We will be given a csv file or excel sheet with different features
# We can use use pandas to read that data and then it gets converted to data frame.
#data frame is a combination of rows and columns and it shows how data exactly like excel sheet


In [38]:
import pandas as pd
import numpy as np

In [39]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1','Row2','Row3','Row4','Row5'], columns=['column1', 'column2', 'column3', 'column4'] )
# pd.DataFrame() to create a data frame
# It takes 3 parameters: data, index means row names, column means column names
#index should be given based on no of rows(available in reshape)
df.head()  

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [40]:
df.to_csv('dataframe.csv')
# this stores above values in a csv file 
# csv = comma seperated values

In [41]:
#Accessing elements
#two ways are there:   .loc, .iloc
#in .loc we focus on indexes but in .iloc we focus on both row index and column index.
# .loc means location, .iloc means index location
#loc just returs the values of given row, iloc shows rows and columns aswell

print(df.loc['Row1'])
print(type(df.loc['Row1']))  #*****

# if any one row or one column then its a 'series'
    #here we are just accessing one row of data
# if more than one row and more than one column its a 'data frame'


column1    0
column2    1
column3    2
column4    3
Name: Row1, dtype: int32
<class 'pandas.core.series.Series'>


In [42]:
df.iloc[0:2, 0:2]

column1  column2
Row1        0        1
Row2        4        5

In [43]:
print(type(df.iloc[0:2, 0:2]))
#this is a data frame because it has more than one row and one column

# in series it included columns names as seperate column but in data frame its not 

<class 'pandas.core.frame.DataFrame'>


In [44]:
df.iloc[:, 1:]

column2  column3  column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [45]:
#convert data frame into array
print(df.iloc[:, 1:].values)   # .values converts this data frame into array
print(df.iloc[:, 1:].values.shape) #shape ***



[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]
(5, 3)


In [46]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [47]:
df['column1'].value_counts()
#returns how many times each element of column 1 has occured

column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [48]:
df['column1'].unique() #returns all the unique values of column1

array([ 0,  4,  8, 12, 16])

In [49]:
df[['column3','column4']]
#this also returns the values present in columns 3,4

column3  column4
Row1        2        3
Row2        6        7
Row3       10       11
Row4       14       15
Row5       18       19

In [50]:
df = pd.read_csv('mercedesbenz.csv')
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [51]:
print(df.info())
#returns no of columns, dtypes, memory usage, total entries 

print()
print(df.describe())
#returns count, mean, stndrd dev, min, max percentiles

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB
None



                ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     

In [52]:
test_df = pd.read_csv('test1.csv', sep=';')
test_df.head()

Unnamed: 0  column1  column2  column3  column4
0       row1        0        1        2        3
1       row2        4        5        6        7
2       row3        8        9       10       11
3       row4       12       13       14       15
4       row4       16       17       18       19

In [53]:
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [54]:
df[df['y']>100]
#prints the elements of y whose values are greater than 100

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

## csv

In [55]:
from io import StringIO, BytesIO

In [56]:
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3\n')

print(type(data))

<class 'str'>


In [57]:
StringIO()

In [58]:
pd.read_csv(StringIO(data), usecols=(['col1','col3']))
# StringIO is used to convert the string data into a file-like object, 
# which can then be read by the pd.read_csv() function.
# The pd.read_csv() function in pandas is designed to read data from a file or a file-like object, not
#  directly from a string that contains CSV data.

col1  col3
0    x     1
1    a     2
2    c     3

In [59]:
df.to_csv('test.csv')

In [60]:
data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')
# no , after every string 

In [61]:
df = pd.read_csv(StringIO(data), dtype=object)
#making data type as object
df

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [62]:
df['a'][1]
#returns a as a string
df['a']
# the whole column is an object but each element in column here is a string

0    1
1    5
2    9
Name: a, dtype: object

In [63]:
df = pd.read_csv(StringIO(data), dtype={'col1':int, 'col2':float, 'col3':'int64'})
print(df)
print()
print(df.dtypes)

   a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

a      int64
b      int64
c      int64
d    float64
dtype: object


In [64]:
## Index columns and training delimiters

In [65]:
data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')

pd.read_csv(StringIO(data), index_col=0)
# elements of column 0 becomes the row indexes

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [66]:
data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')


In [67]:
pd.read_csv(StringIO(data))
#it makes 4,8 as row indexes
# to avoid this
pd.read_csv(StringIO(data), index_col=False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [68]:
## combining usecols and index_cols
pd.read_csv(StringIO(data), usecols=['b','c'], index_col=False)

b    c
0   apple  bat
1  orange  cow

In [79]:
## Quoting and Escape Characters¶. Very useful in NLP
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello, "Bob", nice to see you  5

In [70]:
df=pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',
                 sep='\t')
#arranges tab seperated values

HTTPError: HTTP Error 403: Forbidden

## Read json to csv

In [ ]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(StringIO(Data))

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [ ]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df.head()
# if we dont use header=None it wil treat first row as column names

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [ ]:
#convert json to csv
df.to_csv('wine.csv')

In [73]:
#convert data frame to json
df.to_json(orient='records')
# whenever we create json we need to create the json with respect to records so it takes all records
# If JSON data is a list of records, you should specify orient='records'

'[{"a":1,"b":2,"c":3,"d":4.0},{"a":5,"b":6,"c":7,"d":8.0},{"a":9,"b":10,"c":11,"d":null}]'

## Reading html content

In [ ]:
url = 'https://en.wikipedia.org/wiki/Mobile_country_code'

dfs = pd.read_html(url)
dfs[1]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [6]:
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs = pd.read_html(url_mcc, match='Country', header=0)
dfs[0]
# searches the table in the url that has country field 
#  If you set match='Country', pandas will extract all tables that have a 
# cell with the exact string ‘Country’.

<IPython.core.display.Javascript object>

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

## Reading excel files

In [ ]:
df_excel=pd.read_excel('Excel_Sample.xlsx')
df_excel.head()

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

## Pickling
All pandas objects are equipped with to_pickle methods which use Python’s cPickle module to save data structures to disk using the pickle format.

In [ ]:
df_excel.to_pickle('df_excel')
# creates a pickle with name df_excel 
df = pd.read_pickle('df_excel')
df.head()

# Pickling is used for serializing and de-serializing Python object structures, 
# also called marshalling or flattening. Serialization refers to the process of converting
# an object in memory to a byte stream that can be stored on disk or sent over a network. Later on,
# this character stream can then be retrieved and de-serialized back to a Python object.

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15